"""schema completo

Revision ID: 006c8e80f572
Revises: 
Create Date: 2026-09-17 14:45:38.819095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # noqa: F401
from sqlalchemy.dialects import postgresql

revision: str = '006c8e80f572'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('categoria', sa.String(length=40), nullable=False),
    sa.Column('tipo_solucao', sa.String(length=40), nullable=False),
    sa.Column('precisa_hardware', sa.Boolean(), nullable=False),
    sa.Column('historia', sa.Text(), nullable=False),
    sa.Column('fontes_historicas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('impacto_estimado', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('problema', sa.Text(), nullable=False),
    sa.Column('recurso_local', sa.String(length=200), nullable=False),
    sa.Column('solucao', sa.String(length=200), nullable=False),
    sa.Column('evidencia', sa.String(length=20), nullable=False),
    sa.Column('composicao', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('propriedades', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('aplicacoes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lacunas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('referencias', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('nivel_1_pronto', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('nivel_2_simples', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('nivel_3_completo', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_casos_categoria'), 'casos', ['categoria'], unique=False)
    op.create_index(op.f('ix_casos_numero'), 'casos', ['numero'], unique=True)
    op.create_index(op.f('ix_casos_tipo_solucao'), 'casos', ['tipo_solucao'], unique=False)
    op.create_index(op.f('ix_casos_uf'), 'casos', ['uf'], unique=False)
    op.create_table('noticias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=500), nullable=False),
    sa.Column('resumo', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('fonte', sa.String(length=120), nullable=False),
    sa.Column('categoria', sa.String(length=60), nullable=False),
    sa.Column('severidade', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('municipio', sa.String(length=120), nullable=True),
    sa.Column('metadados', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('publicada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('coletada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_noticias_uf'), 'noticias', ['uf'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.String(length=40), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('municipio', sa.String(length=120), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('evidencias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('caso_id', sa.UUID(), nullable=False),
    sa.Column('afirmacao', sa.Text(), nullable=False),
    sa.Column('nivel', sa.String(length=20), nullable=False),
    sa.Column('fonte', sa.String(length=500), nullable=True),
    sa.Column('doi', sa.String(length=120), nullable=True),
    sa.Column('metadados', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caso_id'], ['casos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidencias_caso_id'), 'evidencias', ['caso_id'], unique=False)
    op.create_table('medicoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('caso_id', sa.UUID(), nullable=True),
    sa.Column('razao_r', sa.Float(), nullable=False),
    sa.Column('razao_g', sa.Float(), nullable=False),
    sa.Column('razao_b', sa.Float(), nullable=False),
    sa.Column('razao_c', sa.Float(), nullable=False),
    sa.Column('resultado', sa.String(length=20), nullable=False),
    sa.Column('confianca', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('municipio', sa.String(length=120), nullable=True),
    sa.Column('metadados', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caso_id'], ['casos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicoes_device_id'), 'medicoes', ['device_id'], unique=False)
    op.create_table('documentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('medicao_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('orgao_destino', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('metadados', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medicao_id'], ['medicoes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documentos')
    op.drop_index(op.f('ix_medicoes_device_id'), table_name='medicoes')
    op.drop_table('medicoes')
    op.drop_index(op.f('ix_evidencias_caso_id'), table_name='evidencias')
    op.drop_table('evidencias')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_noticias_uf'), table_name='noticias')
    op.drop_table('noticias')
    op.drop_index(op.f('ix_casos_uf'), table_name='casos')
    op.drop_index(op.f('ix_casos_tipo_solucao'), table_name='casos')
    op.drop_index(op.f('ix_casos_numero'), table_name='casos')
    op.drop_index(op.f('ix_casos_categoria'), table_name='casos')
    op.drop_table('casos')
    # ### end Alembic commands ###
