"""add conversas e biblioteca

Revision ID: 482d8b609bc0
Revises: e979569a9df7
Create Date: 2026-09-18 15:26:57.759039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # noqa: F401
from sqlalchemy.dialects import postgresql

revision: str = '482d8b609bc0'
down_revision: Union[str, None] = 'e979569a9df7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biblioteca',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('referencia_id', sa.String(length=120), nullable=True),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('resumo', sa.Text(), nullable=True),
    sa.Column('metadados', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biblioteca_usuario_id'), 'biblioteca', ['usuario_id'], unique=False)
    op.create_table('conversas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('mensagens', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversas_session_id'), 'conversas', ['session_id'], unique=False)
    op.create_index(op.f('ix_conversas_usuario_id'), 'conversas', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversas_usuario_id'), table_name='conversas')
    op.drop_index(op.f('ix_conversas_session_id'), table_name='conversas')
    op.drop_table('conversas')
    op.drop_index(op.f('ix_biblioteca_usuario_id'), table_name='biblioteca')
    op.drop_table('biblioteca')
    # ### end Alembic commands ###
