"""add papers table

Revision ID: 640696f62e5e
Revises: 006c8e80f572
Create Date: 2026-09-18 02:26:08.067644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # noqa: F401
from sqlalchemy.dialects import postgresql

revision: str = '640696f62e5e'
down_revision: Union[str, None] = '006c8e80f572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doi', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('titulo', sa.String(length=500), nullable=False),
    sa.Column('autores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('journal', sa.String(length=300), nullable=True),
    sa.Column('tipo', sa.String(length=60), nullable=True),
    sa.Column('citacoes', sa.Integer(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('fonte', sa.String(length=60), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('vezes_usado', sa.Integer(), nullable=False),
    sa.Column('primeira_busca', sa.String(length=300), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_papers_doi'), 'papers', ['doi'], unique=True)
    op.create_index(op.f('ix_papers_titulo'), 'papers', ['titulo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_papers_titulo'), table_name='papers')
    op.drop_index(op.f('ix_papers_doi'), table_name='papers')
    op.drop_table('papers')
    # ### end Alembic commands ###
