"""add contribuicoes votos comentarios

Revision ID: e979569a9df7
Revises: 640696f62e5e
Create Date: 2026-09-18 03:15:14.647789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # noqa: F401
from sqlalchemy.dialects import postgresql

revision: str = 'e979569a9df7'
down_revision: Union[str, None] = '640696f62e5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contribuicoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('autor_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('evidencias', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('caso_relacionado', sa.UUID(), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('municipio', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('validado_por_id', sa.UUID(), nullable=True),
    sa.Column('validado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo_validacao', sa.Text(), nullable=True),
    sa.Column('votos', sa.Integer(), nullable=False),
    sa.Column('visualizacoes', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['caso_relacionado'], ['casos.id'], ),
    sa.ForeignKeyConstraint(['validado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contribuicoes_autor_id'), 'contribuicoes', ['autor_id'], unique=False)
    op.create_index(op.f('ix_contribuicoes_caso_relacionado'), 'contribuicoes', ['caso_relacionado'], unique=False)
    op.create_index(op.f('ix_contribuicoes_status'), 'contribuicoes', ['status'], unique=False)
    op.create_index(op.f('ix_contribuicoes_tipo'), 'contribuicoes', ['tipo'], unique=False)
    op.create_index(op.f('ix_contribuicoes_uf'), 'contribuicoes', ['uf'], unique=False)
    op.create_table('comentarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('autor_id', sa.UUID(), nullable=False),
    sa.Column('contribuicao_id', sa.UUID(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['contribuicao_id'], ['contribuicoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comentarios_autor_id'), 'comentarios', ['autor_id'], unique=False)
    op.create_index(op.f('ix_comentarios_contribuicao_id'), 'comentarios', ['contribuicao_id'], unique=False)
    op.create_table('votos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('contribuicao_id', sa.UUID(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contribuicao_id'], ['contribuicoes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_votos_contribuicao_id'), 'votos', ['contribuicao_id'], unique=False)
    op.create_index(op.f('ix_votos_usuario_id'), 'votos', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votos_usuario_id'), table_name='votos')
    op.drop_index(op.f('ix_votos_contribuicao_id'), table_name='votos')
    op.drop_table('votos')
    op.drop_index(op.f('ix_comentarios_contribuicao_id'), table_name='comentarios')
    op.drop_index(op.f('ix_comentarios_autor_id'), table_name='comentarios')
    op.drop_table('comentarios')
    op.drop_index(op.f('ix_contribuicoes_uf'), table_name='contribuicoes')
    op.drop_index(op.f('ix_contribuicoes_tipo'), table_name='contribuicoes')
    op.drop_index(op.f('ix_contribuicoes_status'), table_name='contribuicoes')
    op.drop_index(op.f('ix_contribuicoes_caso_relacionado'), table_name='contribuicoes')
    op.drop_index(op.f('ix_contribuicoes_autor_id'), table_name='contribuicoes')
    op.drop_table('contribuicoes')
    # ### end Alembic commands ###
